import {Braces,Binary,KeyRound,Fingerprint,Regex,QrCode,Palette,FileCode2,Hash,Database,Clock3,Link2,CalendarClock,CaseSensitive,Type,GitCompare,Table,FileJson,FileSpreadsheet,Binary as BinaryIcon,Code2,KeySquare,ListTree,Terminal,type LucideIcon} from "lucide-react";

export type Tool={slug:string;name:string;description:string;category:string;icon:LucideIcon;featured?:boolean;status?:"ready"|"soon";isNew?:boolean;metaDescription:string;seoSummary:string;seoPoints:readonly string[]};

export const tools:Tool[]=[
{slug:"json-formatter",name:"JSON Formatter",description:"Format, validate and inspect JSON instantly.",category:"Formatters",icon:Braces,featured:true,status:"ready",metaDescription:"Format, validate, minify, and inspect JSON locally in your browser with DevHub's free JSON formatter.",seoSummary:"Use this JSON formatter to clean up API responses, check syntax before a deploy, and inspect nested objects without sending your data to a server.",seoPoints:["Formats and validates readable JSON in the browser.","Useful for API responses, configuration files, and debugging payloads.","Invalid syntax is reported before formatting so mistakes are easier to find."]},
{slug:"base64",name:"Base64",description:"Encode and decode text locally.",category:"Converters",icon:Binary,featured:true,status:"ready",metaDescription:"Encode and decode Base64 text locally in your browser with a fast, private developer utility.",seoSummary:"Convert text to and from Base64 when working with API payloads, tokens, data URLs, or small encoded values.",seoPoints:["Supports local Base64 encoding and decoding.","Useful for debugging headers, payload fragments, and data URL content.","Your input stays in the browser during the deterministic conversion."]},
{slug:"jwt-decoder",name:"JWT Decoder",description:"Inspect token headers and payloads safely.",category:"Security",icon:KeyRound,featured:true,status:"ready",metaDescription:"Decode JWT headers and payloads locally to inspect claims without verifying the token signature.",seoSummary:"Inspect a JWT header and payload during development without uploading the token. This tool decodes claims but does not verify signatures.",seoPoints:["Decodes the header and payload segments locally.","Helps inspect claims such as subject, issuer, audience, and expiry.","JWT decoding is not signature verification and must not be treated as authentication."]},
{slug:"uuid-generator",name:"UUID Generator",description:"Generate secure UUIDs in bulk.",category:"Generators",icon:Fingerprint,featured:true,status:"ready",metaDescription:"Generate UUIDs in bulk with browser-based randomness using DevHub's free UUID generator.",seoSummary:"Create identifiers for tests, fixtures, database records, and API examples without repeating manual UUID formatting.",seoPoints:["Generates multiple UUID values in one run.","Uses browser cryptographic randomness for generated identifiers.","Values are created locally and are not stored by DevHub."]},
{slug:"regex-tester",name:"Regex Tester",description:"Test expressions with live match details.",category:"Text",icon:Regex,featured:true,status:"ready",metaDescription:"Test regular expressions locally with live matches, groups, and readable result details.",seoSummary:"Check a regular expression against sample text while reviewing matches and groups. Use the tester for development and debugging, not as a formal ReDoS proof.",seoPoints:["Tests a pattern against input text in the browser.","Shows match details and capture information as you iterate.","Input and pattern complexity guards reduce common excessive-backtracking risks."]},
{slug:"qr-generator",name:"QR Generator",description:"Create crisp, customizable QR codes.",category:"Generators",icon:QrCode,featured:true,status:"ready",metaDescription:"Create downloadable QR codes locally from text or URLs with DevHub's free QR generator.",seoSummary:"Turn a short URL, contact value, or message into a QR code directly in the browser for quick local generation.",seoPoints:["Generates QR images from text or URL input.","Useful for prototypes, documentation, events, and local testing.","The source value is processed in the browser and is not sent to DevHub."]},
{slug:"color-converter",name:"Color Converter",description:"Convert HEX, RGB and HSL colors.",category:"Design",icon:Palette,status:"ready",metaDescription:"Convert HEX, RGB, and HSL color values locally with a quick browser-based color converter.",seoSummary:"Translate colors between HEX, RGB, and HSL while checking the equivalent value for design systems and CSS work.",seoPoints:["Converts common HEX, RGB, and HSL formats.","Useful when translating design tokens into CSS values.","Invalid color syntax is reported before a conversion is shown."]},
{slug:"markdown-preview",name:"Markdown Preview",description:"Write and preview safe Markdown side by side.",category:"Editors",icon:FileCode2,status:"ready",metaDescription:"Preview safe Markdown side by side and export local HTML without uploading your document.",seoSummary:"Draft README sections, notes, and documentation with a live Markdown preview and a safe, local HTML export.",seoPoints:["Renders headings, lists, tables, quotes, links, and fenced code.","Escapes unsafe raw HTML and does not fetch remote images.","Markdown text and generated HTML remain in the browser."]},
{slug:"hash-generator",name:"Hash Generator",description:"Generate SHA hashes locally with Web Crypto.",category:"Security",icon:Hash,status:"ready",metaDescription:"Generate SHA-256 and related hashes locally with the browser Web Crypto API.",seoSummary:"Calculate a digest for a text value when comparing files, checking fixtures, or debugging deterministic data transformations.",seoPoints:["Uses Web Crypto for browser-based hashing.","Useful for checksums and comparisons during development.","Hashing is not password hashing and does not make weak secrets safe."]},
{slug:"sql-formatter",name:"SQL Formatter",description:"Make common SQL statements readable.",category:"Formatters",icon:Database,status:"ready",metaDescription:"Format common SQL statements into readable, indented queries locally in your browser.",seoSummary:"Turn compact SQL into a more readable layout when reviewing queries, debugging generated statements, or preparing examples.",seoPoints:["Formats common SELECT, INSERT, UPDATE, and DELETE structures.","Improves readability without executing the query.","SQL support is intentionally lightweight and should be checked against your database dialect."]},
{slug:"cron-parser",name:"Cron Parser",description:"Translate five-field cron expressions.",category:"Reference",icon:Clock3,status:"ready",metaDescription:"Parse five-field cron expressions locally and explain their schedule in plain language.",seoSummary:"Translate a standard five-field cron expression into a readable schedule before adding it to a server, CI pipeline, or task runner.",seoPoints:["Explains minute, hour, day, month, and weekday fields.","Useful for checking recurring automation schedules.","The parser covers the common five-field format rather than every vendor-specific extension."]},
{slug:"url-encoder",name:"URL Encoder",description:"Encode and decode URL components safely.",category:"Converters",icon:Link2,status:"ready",metaDescription:"Encode and decode URL components locally for query parameters, paths, and API examples.",seoSummary:"Prepare URL-safe values or inspect encoded query components without sending the URL content to a remote service.",seoPoints:["Encodes and decodes URI components in the browser.","Useful for query strings, API examples, and redirect debugging.","The tool does not fetch or visit the URL you enter."]},
{slug:"timestamp-converter",name:"Timestamp Converter",description:"Convert Unix timestamps and ISO dates locally.",category:"Converters",icon:CalendarClock,status:"ready",metaDescription:"Convert Unix timestamps and ISO 8601 dates locally with a fast browser-based date utility.",seoSummary:"Translate Unix timestamps and ISO dates while debugging logs, API responses, event payloads, and scheduling data.",seoPoints:["Converts common Unix timestamp and ISO date values.","Useful for comparing log times and API event fields.","Conversion runs locally and does not depend on a network time service."]},
{slug:"case-converter",name:"Case Converter",description:"Switch text between camel, snake, kebab and title case.",category:"Text",icon:CaseSensitive,status:"ready",metaDescription:"Convert text between camelCase, snake_case, kebab-case, and title case locally.",seoSummary:"Normalize variable names, headings, labels, and slugs between common casing styles during coding and content workflows.",seoPoints:["Supports camel, snake, kebab, and title case transformations.","Useful for API fields, filenames, headings, and CSS naming.","Text is transformed in the browser without a remote conversion service."]},
{slug:"slug-generator",name:"Slug Generator",description:"Turn any heading into a clean URL slug.",category:"Text",icon:Type,status:"ready",metaDescription:"Generate clean, readable URL slugs from headings and titles with a local browser tool.",seoSummary:"Create a normalized slug for an article heading, documentation page, or route while keeping the transformation predictable and local.",seoPoints:["Normalizes headings into lowercase URL-friendly text.","Removes unsuitable punctuation and separates words consistently.","Review the result for your routing and editorial conventions before publishing."]},
{slug:"text-diff",name:"Text Diff",description:"Compare two text versions line by line.",category:"Text",icon:GitCompare,status:"ready",metaDescription:"Compare two text versions line by line with a local browser-based text diff tool.",seoSummary:"Review edits to configuration, documentation, prompts, or code snippets by comparing two text versions side by side.",seoPoints:["Compares two text values line by line.","Useful for spotting additions, removals, and changed lines.","Comparison stays in the browser and does not create a hosted diff link."]},
{slug:"text-stats",name:"Text Statistics",description:"Count characters, words, lines and reading time.",category:"Text",icon:FileCode2,status:"ready",metaDescription:"Count words, characters, lines, and estimated reading time locally with DevHub.",seoSummary:"Measure a text value when preparing documentation, release notes, prompts, or content with simple local statistics.",seoPoints:["Counts characters, words, and lines.","Shows an estimated reading-time signal for the entered text.","Statistics are calculated locally and are not saved by default."]},
{slug:"json-to-csv",name:"JSON to CSV",description:"Convert a JSON array of objects into CSV rows.",category:"Converters",icon:Table,status:"ready",metaDescription:"Convert a JSON array of objects into CSV rows locally for quick developer data transformation.",seoSummary:"Turn a header-compatible JSON array into CSV when moving sample data between APIs, spreadsheets, and local test fixtures.",seoPoints:["Converts arrays of objects into CSV with a header row.","Useful for small exports and test-data preparation.","The conversion is local and does not upload your JSON."]},
{slug:"csv-to-json",name:"CSV to JSON",description:"Turn CSV with a header row into structured JSON.",category:"Converters",icon:FileSpreadsheet,status:"ready",metaDescription:"Convert header-based CSV text into structured JSON locally in your browser.",seoSummary:"Parse a CSV document with a header row into JSON objects for API fixtures, debugging, and local data inspection.",seoPoints:["Uses the first CSV row as object keys.","Useful for moving tabular samples into JSON-based workflows.","Review quoted values and delimiter assumptions for complex CSV files."]},
{slug:"json-to-yaml",name:"JSON to YAML",description:"Render JSON as readable YAML locally.",category:"Converters",icon:FileJson,status:"ready",metaDescription:"Convert valid JSON into readable YAML locally for configuration and documentation workflows.",seoSummary:"Render JSON configuration or examples as YAML when preparing manifests, documentation, or human-readable settings files.",seoPoints:["Accepts valid JSON and produces structured YAML.","Useful for configuration examples and cross-format review.","Invalid JSON is reported before conversion takes place."]},
{slug:"number-base",name:"Number Base Converter",description:"Convert between decimal, hex, octal and binary.",category:"Converters",icon:BinaryIcon,status:"ready",metaDescription:"Convert numbers between decimal, hexadecimal, octal, and binary values locally.",seoSummary:"Translate a number between common bases while working with bitmasks, colors, permissions, encodings, and low-level data.",seoPoints:["Supports decimal, hexadecimal, octal, and binary values.","Useful for checking representations in code and systems work.","The converter handles numeric values locally without external lookup."]},
{slug:"html-entities",name:"HTML Entities",description:"Encode and decode HTML entities safely.",category:"Text",icon:Code2,status:"ready",metaDescription:"Encode and decode HTML entities locally for markup, escaping, and content debugging.",seoSummary:"Inspect or transform characters such as ampersands, angle brackets, and quotes when debugging HTML or escaped content.",seoPoints:["Encodes and decodes common HTML entities.","Useful for markup debugging and escaped text inspection.","The tool does not render or fetch the HTML you enter."]},
{slug:"query-parser",name:"Query String Parser",description:"Break a URL query string into structured parameters.",category:"Text",icon:ListTree,status:"ready",metaDescription:"Parse URL query strings into readable key-value parameters locally without fetching the URL.",seoSummary:"Break a query string into keys and values when debugging links, filters, redirects, or API request parameters.",seoPoints:["Parses query parameters into structured key-value output.","Useful for repeated parameters and redirect debugging.","Only the text is parsed; no network request is made to the URL."]},
{slug:"password-generator",name:"Password Generator",description:"Generate strong passwords with Web Crypto randomness.",category:"Security",icon:KeySquare,status:"ready",metaDescription:"Generate random passwords locally with browser cryptographic randomness and configurable length.",seoSummary:"Create a random password for testing or account setup without transmitting the generated value to DevHub.",seoPoints:["Generates configurable-length passwords locally.","Uses browser cryptographic randomness for generation.","Use a dedicated password manager and follow the destination service's requirements."]},
{slug:"yaml-formatter",name:"YAML Formatter",description:"Format and validate common YAML indentation locally.",category:"Formatters",icon:FileJson,status:"ready",metaDescription:"Format and validate common YAML indentation locally in your browser.",seoSummary:"Clean up YAML configuration and catch common indentation mistakes without sending the document to a server.",seoPoints:["Normalizes common two-space YAML indentation.","Rejects tabs and unsafe indentation jumps with readable errors.","Processing stays in the browser for local configuration review."]},
{slug:"xml-formatter",name:"XML Formatter",description:"Pretty-print and validate well-formed XML locally.",category:"Formatters",icon:FileCode2,status:"ready",metaDescription:"Pretty-print and validate well-formed XML locally in your browser.",seoSummary:"Format XML documents into a readable tree while catching mismatched tags and missing root elements locally.",seoPoints:["Pretty-prints nested XML with readable indentation.","Validates a single well-formed root and matching closing tags.","Does not fetch external entities or send your XML to a server."]},
{slug:"markdown-linter",name:"Markdown Linter",description:"Find common Markdown structure and style issues.",category:"Editors",icon:ListTree,status:"ready",metaDescription:"Find common Markdown structure and style issues locally with DevHub.",seoSummary:"Review Markdown headings, links, whitespace, and code fences before publishing documentation or a README.",seoPoints:["Reports common Markdown style findings with line numbers.","Checks heading hierarchy, empty links, image alt text, and fenced blocks.","Linting is deterministic and runs locally in the browser."]},
{slug:"url-parser",name:"URL Parser",description:"Inspect URL parts, query parameters, and fragments.",category:"Converters",icon:Link2,status:"ready",metaDescription:"Inspect URL components and query parameters locally in your browser.",seoSummary:"Break a URL into its protocol, host, path, query values, and fragment without visiting or fetching it.",seoPoints:["Shows protocol, host, port, path, search, and hash components.","Groups repeated query keys into arrays for easier inspection.","The parser never makes a network request to the entered URL."]},
{slug:"gitignore-generator",name:"Gitignore Generator",description:"Generate focused .gitignore rules for common stacks.",category:"Generators",icon:GitCompare,status:"ready",metaDescription:"Generate focused .gitignore rules for common development stacks locally.",seoSummary:"Combine practical ignore rules for Node, Next.js, VS Code, operating systems, and environment files into one local .gitignore.",seoPoints:["Combines multiple built-in stack templates.","Deduplicates rules and supports common template aliases.","The generated file is created locally and is not uploaded."]},
{slug:"json-to-typescript",name:"JSON to TypeScript",description:"Generate readable TypeScript interfaces from JSON.",category:"Converters",icon:Type,status:"ready",metaDescription:"Generate TypeScript interfaces from JSON locally in your browser.",seoSummary:"Turn JSON examples into inferred TypeScript interfaces for API fixtures, configuration, and frontend development.",seoPoints:["Infers primitive, array, nested-object, and nullable field types.","Creates readable exported interfaces for object-shaped JSON.","Conversion is deterministic and stays in the browser."]},
{slug:"curl-converter",name:"cURL Converter",description:"Convert cURL commands to Fetch, Axios, Python, and Go.",category:"Converters",icon:Terminal,featured:true,isNew:true,status:"ready",metaDescription:"Convert cURL commands into JavaScript Fetch, Axios, Python Requests, and Go locally in your browser.",seoSummary:"Turn browser or API cURL commands into clean, idiomatic code for frontend or backend applications without sending your requests to an external service.",seoPoints:["Converts cURL into JavaScript Fetch, Axios, Python, Go, Node.js, and PHP.","Extracts methods, headers, query parameters, basic auth, and request payloads.","All conversion is deterministic and runs locally in your browser."]},
{slug:"yaml-to-json",name:"YAML to JSON",description:"Convert YAML configuration into structured JSON.",category:"Converters",icon:FileJson,featured:true,isNew:true,status:"ready",metaDescription:"Convert YAML configuration into structured, formatted JSON locally in your browser with DevHub.",seoSummary:"Transform YAML files into structured JSON for API payloads, manifests, configuration pipelines, and local development.",seoPoints:["Converts nested YAML mappings, lists, and scalars to JSON.","Runs completely locally in the browser with zero external calls.","Validates syntax and reports indentation or mapping errors clearly."]}
];


export const categoryDescriptions:Record<string,string>={
  Formatters:"Clean, validate, and restructure developer text and data without leaving the browser. These utilities are useful for API payloads, queries, and configuration files.",
  Converters:"Move developer data between common representations for APIs, configuration, URLs, dates, and test fixtures while keeping deterministic transformations local.",
  Security:"Inspect or generate security-related values with clear boundaries. DevHub explains what each browser tool can do and what it does not verify.",
  Generators:"Create identifiers, QR codes, and other reusable values locally for prototypes, tests, documentation, and everyday development work.",
  Text:"Transform, compare, parse, and measure text for coding, documentation, URLs, and content workflows with browser-based utilities.",
  Design:"Translate common color values between formats so design tokens and CSS examples stay easy to inspect and reuse.",
  Editors:"Draft and preview structured content locally with a safe rendering boundary and tools designed for documentation workflows.",
  Reference:"Interpret common developer notation and schedules with concise explanations before you commit them to a system or automation job."
};

export const categories=[...new Set(tools.map(tool=>tool.category))];

// Performance Optimization:
// Pre-computed map for O(1) slug lookup instead of O(N) array scanning via tools.find()
const toolMap = new Map<string, Tool>(tools.map((tool) => [tool.slug, tool]));

// Performance Optimization:
// Pre-grouped tools by category to avoid repeated filtering of the tools array during component renders
export const toolsByCategory: Record<string, Tool[]> = categories.reduce<Record<string, Tool[]>>((acc, category) => {
  acc[category] = tools.filter((tool) => tool.category === category);
  return acc;
}, {});

export function getTool(slug: string) {
  return toolMap.get(slug);
}
