import * as Utils from './utils';
// Destructure what we need (or just use Utils.)
// Actually, since the lines might use the util functions directly, we should just import them all:
import { EngineResult, escapeHtml, textEncoder, fatalTextDecoder, bytesToBase64, decodeBase64Bytes, decodeUtf8, decodeJwtPart, MAX_REGEX_PATTERN_LENGTH, MAX_MARKDOWN_LENGTH, safeMarkdownHref, formatInlineMarkdown, splitMarkdownTableRow, isMarkdownTableSeparator, renderMarkdownTable, parseCsvRows, htmlEntityMap, MAX_BATCH_TOOL_LENGTH, ensureBatchInput, gitignoreTemplates, typeScriptIdentifier } from './utils';

export function transformUrl(input:string,mode:"encode"|"decode"):EngineResult{return {output:mode==="encode"?encodeURIComponent(input):decodeURIComponent(input),meta:mode==="encode"?"Encoded component":"Decoded component"}}
export function parseQueryString(input:string):EngineResult{const value=input.trim();if(!value)throw new Error("Enter a URL or a query string.");const queryIndex=value.indexOf("?");const query=queryIndex>=0?value.slice(queryIndex+1):value;const params=new URLSearchParams(query.split("#")[0]);const entries=[...params.entries()];if(entries.length===0)throw new Error("No query parameters found.");const grouped:Record<string,string|string[]>={};for(const [key,item] of entries){const existing=grouped[key];if(existing===undefined)grouped[key]=item;else if(Array.isArray(existing))existing.push(item);else grouped[key]=[existing,item]}return {output:JSON.stringify(grouped,null,2),meta:`${entries.length} parameter${entries.length===1?"":"s"}`}}
export function parseUrl(input:string):EngineResult{const value=ensureBatchInput(input,"Enter a URL or query string.").trim();const normalized=value.startsWith("?")?`https://devhub.local/${value}`:value.includes("://")?value:value.startsWith("/")?`https://devhub.local${value}`:`https://${value}`;let url:URL;try{url=new URL(normalized)}catch{throw new Error("Enter a valid URL with a host, path, or query string.")}const query:Record<string,string|string[]>={};for(const [key,item] of url.searchParams.entries()){const existing=query[key];if(existing===undefined)query[key]=item;else if(Array.isArray(existing))existing.push(item);else query[key]=[existing,item]}return {output:JSON.stringify({href:url.href,protocol:url.protocol,username:url.username,host:url.host,hostname:url.hostname,port:url.port,pathname:url.pathname,search:url.search,hash:url.hash,query},null,2),meta:`Parsed locally — ${url.searchParams.size} quer${url.searchParams.size===1?"y":"ies"}`}}
export function transformHtmlEntities(input:string,mode:"encode"|"decode"):EngineResult{if(mode==="encode")return {output:input.replace(/[&<>"']/g,char=>htmlEntityMap[char]!),meta:"Entities encoded"};const named:Record<string,string>={amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:" "};return {output:input.replace(/&(#x?[0-9a-fA-F]+|[a-zA-Z]+);/g,(match,entity:string)=>{if(entity.startsWith("#")){const code=entity[1]==="x"||entity[1]==="X"?parseInt(entity.slice(2),16):parseInt(entity.slice(1),10);return Number.isFinite(code)&&code>=0&&code<=0x10ffff?String.fromCodePoint(code):match}return named[entity.toLowerCase()]??match}),meta:"Entities decoded"}}
export function convertColor(input:string):EngineResult{const hex=input.trim().replace("#","");if(!/^[0-9a-f]{6}$/i.test(hex))throw new Error("Enter a six-digit HEX color.");const [r,g,b]=[0,2,4].map(i=>parseInt(hex.slice(i,i+2),16));const max=Math.max(r,g,b)/255,min=Math.min(r,g,b)/255;let h=0;const l=(max+min)/2,d=max-min;const s=d===0?0:d/(1-Math.abs(2*l-1));if(d){if(max===r/255)h=60*(((g-b)/255/d)%6);else if(max===g/255)h=60*((b-r)/255/d+2);else h=60*((r-g)/255/d+4)}if(h<0)h+=360;return {output:`HEX  #${hex.toUpperCase()}\nRGB  rgb(${r}, ${g}, ${b})\nHSL  hsl(${Math.round(h)}, ${Math.round(s*100)}%, ${Math.round(l*100)}%)`,meta:`rgb(${r}, ${g}, ${b})`}}