"use client";

import { useId, useState } from "react";
import { LifeBuoy, Loader2 } from "lucide-react";
import { explainToolError } from "@/lib/ai/explain-error";
import {
  AI_ERROR_MESSAGE_LIMIT,
  describeDestination,
} from "@/lib/ai/provider-config";
import { useAiConfig } from "@/lib/ai/use-ai-config";
import { engines } from "@/lib/engine-registry";
import { tools } from "@/lib/tools";
import styles from "./workflow-planner.module.css";

export function ErrorExplainer() {
  const fieldId = useId();
  const { config, configured } = useAiConfig();
  const [engineId, setEngineId] = useState(engines[0]?.id ?? "");
  const [message, setMessage] = useState("");
  const [consent, setConsent] = useState(false);
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string>();
  const [explanation, setExplanation] = useState<string>();

  const destination = config ? describeDestination(config) : undefined;
  const canSubmit = configured && consent && !pending && message.trim().length > 0;

  async function submit(event: React.FormEvent) {
    event.preventDefault();
    if (!config || !canSubmit) return;
    setPending(true);
    setError(undefined);
    setExplanation(undefined);
    const result = await explainToolError({ engineId, message, config });
    setPending(false);
    setConsent(false);
    if (!result.ok) {
      setError(result.error);
      return;
    }
    setExplanation(result.explanation);
  }

  return (
    <section className={styles.panel} aria-labelledby={`${fieldId}-title`}>
      <header>
        <span className={styles.icon}>
          <LifeBuoy size={16} />
        </span>
        <div>
          <h2 id={`${fieldId}-title`}>Explain a tool error</h2>
          <p>
            Paste the error message a tool returned. Only the tool identity and
            that message are sent — never the input that produced it.
          </p>
        </div>
      </header>

      {!configured ? (
        <p className={styles.gate} role="status">
          Add your own AI provider above to enable error explanations.
        </p>
      ) : null}

      <form onSubmit={submit} className={styles.form}>
        <label htmlFor={`${fieldId}-tool`}>
          <span>Tool</span>
          <select
            id={`${fieldId}-tool`}
            value={engineId}
            disabled={!configured}
            onChange={(event) => setEngineId(event.target.value)}
          >
            {engines.map((engine) => (
              <option key={engine.id} value={engine.id}>
                {tools.find((tool) => tool.slug === engine.id)?.name ??
                  engine.id}
              </option>
            ))}
          </select>
        </label>

        <label htmlFor={`${fieldId}-message`}>
          <span>Error message</span>
          <textarea
            id={`${fieldId}-message`}
            value={message}
            rows={3}
            maxLength={AI_ERROR_MESSAGE_LIMIT}
            disabled={!configured}
            placeholder="Unexpected token } in JSON at position 42"
            onChange={(event) => setMessage(event.target.value)}
          />
        </label>
        <p className={styles.counter}>
          {message.length}/{AI_ERROR_MESSAGE_LIMIT} characters
        </p>

        <label className={styles.consent}>
          <input
            type="checkbox"
            checked={consent}
            disabled={!configured}
            onChange={(event) => setConsent(event.target.checked)}
          />
          <span>
            Send the tool name and this error message
            {destination ? ` to ${destination}` : ""}. Remove anything private
            from the message first.
          </span>
        </label>

        <button type="submit" className={styles.primary} disabled={!canSubmit}>
          {pending ? (
            <Loader2 className={styles.spin} size={15} />
          ) : (
            <LifeBuoy size={15} />
          )}
          {pending ? "Asking…" : "Explain error"}
        </button>
      </form>

      {error ? (
        <p className={styles.error} role="alert">
          {error}
        </p>
      ) : null}
      {explanation ? (
        <div className={styles.result}>
          <h3>Explanation</h3>
          <p>{explanation}</p>
          <p className={styles.meta}>
            Generated by your provider. Verify before acting on it.
          </p>
        </div>
      ) : null}
    </section>
  );
}
